# Generated by Django 3.1.4 on 2020-12-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osobniinformace',
            options={'permissions': (('Mediátor', 'Mediátor'), ('Správce', 'Správce'))},
        ),
        migrations.RenameField(
            model_name='osobniinformace',
            old_name='email',
            new_name='Email',
        ),
        migrations.AddField(
            model_name='osobniinformace',
            name='datum_vystaveni_lekarskeho_potvrzeni',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='osobniinformace',
            name='je_zkontrolovan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='osobniinformace',
            name='gdpr',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='gdpr'),
        ),
        migrations.AlterField(
            model_name='osobniinformace',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='osobniinformace',
            name='lekarske_potvrzeni',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='doktor'),
        ),
    ]
