# Generated by Django 3.1.4 on 2020-12-21 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spravce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skupina',
            name='clenove',
            field=models.ManyToManyField(blank=True, through='spravce.Clenstvi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='clenstvi',
            unique_together={('skupina', 'user')},
        ),
    ]
