# Generated by Django 3.1.4 on 2020-12-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spravce', '0003_auto_20201221_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('popisek', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='skupina',
            name='nazev',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
