# Generated by Django 3.1.4 on 2020-12-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prispevekpromediatora',
            name='file',
        ),
        migrations.AlterField(
            model_name='galerie',
            name='file',
            field=models.FileField(upload_to='mediator/'),
        ),
    ]
