# Generated by Django 3.1.4 on 2020-12-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediator', '0002_auto_20201206_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='prispevekpromediatora',
            name='file',
            field=models.FileField(default='neco.jpg', upload_to='mediator_files/'),
        ),
        migrations.DeleteModel(
            name='Galerie',
        ),
    ]
