# Generated by Django 3.1.4 on 2020-12-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediator', '0003_auto_20201207_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prispevekpromediatora',
            name='file',
            field=models.FileField(upload_to='mediator_files/'),
        ),
    ]
