# Generated by Django 3.1.4 on 2020-12-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediator', '0005_auto_20201208_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prispevekfiles',
            name='file',
            field=models.FileField(upload_to='prispevky/tady/'),
        ),
    ]
