# Generated by Django 3.1.4 on 2020-12-11 09:47

from django.db import migrations, models
import mediator.models


class Migration(migrations.Migration):

    dependencies = [
        ('mediator', '0007_auto_20201208_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prispevekfiles',
            name='file',
            field=models.FileField(default='default.txt', upload_to=mediator.models.PrispevekFiles.path),
        ),
    ]
