# Generated by Django 3.1.4 on 2020-12-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediator', '0012_auto_20201212_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='fb_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='createpost',
            name='ig_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
